---
title: "Initial vs Final Colocation"
author: "Hamish Huggard"
date: "January 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data

```{r book_keeping}
library(RPostgreSQL)
library(rpart)
library(reshape2)
library(zoo)
library(ggplot2)
library(MASS)
library(gridExtra)

# Set working directory
setwd("c:\\Users\\Hammo\\Documents\\smoke emissions project\\code_final")

# Database login details (not in GitHub repo)
load("access.Rda")

# Connect to database
p <- dbDriver("PostgreSQL")
con <- dbConnect(p,
                 user=access$user,
                 password=access$pwd,
                 host='penap-data.dyndns.org',
                 dbname='cona',
                 port=5432)
```

```{r load_ecan}
# Load ECan data (stored locally)
ecan <- read.csv('RangioraWinter2016.csv',stringsAsFactors=FALSE)
names(ecan) <- c('date','time','wind.speed','wind.dir','wind.dir.std','wind.speed.std',
                 'wind.max','co','temp.ground','temp.2m','temp.6m','pm10',
                 'pm2.5','pm.course')
ecan$date <- as.POSIXct(ecan$date,format = '%m/%d/%Y %H:%M', tz='Etc/GMT-12')
ecan$time <- NULL # this is included in date
```

```{r load_odin}
# ECan site has siteid=18
odin.raw <-dbGetQuery(con,"SELECT d.recordtime AT TIME ZONE 'NZST' AS date,
                            i.serialn as serial, s.name as label,
                            d.value::numeric as val
                           FROM data.fixed_data as d,  
                            admin.sensor as s, admin.instrument as i
                           WHERE s.id = d.sensorid
                            AND s.instrumentid = i.id
                            AND i.name = 'ODIN-SD-3'
                            AND d.siteid = 18
                            AND (i.serialn = 'ODIN-109'
                             OR i.serialn = 'ODIN-102' 
                             OR i.serialn = 'ODIN-105'
                             OR i.serialn = 'ODIN-107'
                             OR i.serialn = 'ODIN-108'
                             OR i.serialn = 'ODIN-109'
                             OR i.serialn = 'ODIN-113'
                             OR i.serialn = 'ODIN-115')
                            AND ((d.recordtime BETWEEN '2016-07-11 00:00 NZST'
                              AND '2016-07-26 00:00 NZST')
                             OR (d.recordtime BETWEEN '2016-10-03 00:00 NZST'
                              AND '2016-10-19 00:00 NZST'))
                            AND NOT (d.recordtime BETWEEN '2016-09-25 02:00 NZST'
                             AND '2016-09-25 03:00 NZST')
                            AND (s.name = 'PM2.5'
                             OR s.name = 'Temperature'
                             OR s.name = 'RH')
                           ORDER BY date;") 

# 02:01 to 02:59 on 2016-09-25 is excluded because this is when the switch to NZST occurs.
# Without the exclusion clause the timestamps will truncate at 'day'.

# Truncate seconds from timestamps
odin.raw$date <- trunc(odin.raw$date,'min')
odin.raw$date <- as.POSIXct(odin.raw$date) # the above converted it to POSIXlt

# Fix daylight savings bug
ds.time <- as.POSIXct('09/25/2016 02:00',format = '%m/%d/%Y %H:%M', tz='Etc/GMT-12')
odin.raw[odin.raw$date > ds.time, 'date'] <- 
  odin.raw[odin.raw$date > ds.time, 'date'] + 60*60
```

## Preprocessing

```{r odin_preprocessing}
serials <- unique(odin.raw$serial)
odins <- list()

for (i in 1:length(serials)) {
  
  this.odin <- dcast(odin.raw[odin.raw$serial==serials[i],], 
                     date~label, value.var='val', fun.aggregate=mean)
  
  # Make column names easier to type
  names(this.odin) <- tolower(names(this.odin))
  names(this.odin)[which(names(this.odin)=="temperature")] <- "temp"
  odins[[i]] <- this.odin
  
}

# Change ODIN serials from ODIN-x to odin.x
tidy.serial <- function(serialn) paste0('odin.',substring(serialn,6,8))
names(odins) <- sapply(serials,FUN=tidy.serial)
```

```{r merge}
data <- ecan

for (j in 1:length(odins)) {
  
  odin <- odins[[j]]
  
  # Make sure that there is a odin entry for each minute
  dates <- data.frame(date=seq(odin$date[1],odin$date[nrow(odin)],by='mins'))
  odin <- merge(odin,dates,by="date",all=TRUE)
  
  # Change the ODIN measurements from 1 min averages to 1 hour averages
  odin.zoo <- zoo( odin[,2:ncol(odin)] )
  odin.roll.apply <- rollapply(odin.zoo,width=60,by=1,FUN=mean,align="left",na.rm=TRUE)
  odin.avgs <- odin[1:nrow(odin.roll.apply),]
  odin.avgs[,2:ncol(odin)] <- odin.roll.apply
  
  # Take timestamps at the end of the hour average following ECan convention
  odin.avgs$date <- odin.avgs$date + 60*60 
  
  # Purge NaNs
  odin.avgs <- odin.avgs[!is.nan(odin.avgs$pm2.5),]
  odin.avgs <- odin.avgs[!is.nan(odin.avgs$rh),]
  odin.avgs <- odin.avgs[!is.nan(odin.avgs$temp),]
  names(odin.avgs) <- c('date',paste0(names(odin.avgs),'.',names(odins)[j])[2:ncol(odin)])
  data <- merge(data,odin.avgs,by='date',all=FALSE)
}
```

## Build Models

```{r make_models}
# september is a good place to split
split.time <- as.POSIXct('09/01/2016 00:00',format = '%m/%d/%Y %H:%M',tz='Etc/GMT-12')
data.init <- data[data$date < split.time,]
data.fin <- data[data$date > split.time,]

# Check the length
nrow(data.init)
nrow(data.fin)

coefs.init <- data.frame(odin.n=NA,cnst=NA,pm2.5=NA,temp=NA,rh=NA,
                         cnst.std=NA,pm2.5.std=NA,temp.std=NA,rh.std=NA)
coefs.fin <- data.frame(odin.n=NA,cnst=NA,pm2.5=NA,temp=NA,rh=NA,
                         cnst.std=NA,pm2.5.std=NA,temp.std=NA,rh.std=NA)

for (i in 1:length(odins)) {
  
  odin.name <- names(odins)[i]
  odin.vars <- paste0(c('pm2.5','temp','rh'),'.',odin.name)
  eval(parse(text=paste0('form <- pm2.5 ~ ', paste(odin.vars,collapse='+'))))
  
  # Initial coefficients
  this.init.coefs <- summary(lm(form,data=data.init))$coefficients
  coefs.init[i,'odin.n'] <- as.integer(substring(odin.name,6,8)) - 0.1
  coefs.init[i,2:9] <- this.init.coefs[1:8]
  
  # Final coefficients
  this.fin.coefs <- summary(lm(form,data=data.fin))$coefficients
  coefs.fin[i,'odin.n'] <- as.integer(substring(odin.name,6,8)) + 0.1
  coefs.fin[i,2:9] <- this.fin.coefs[1:8]
  
}

coefs.init
coefs.fin

# Percentage changes in each coefficient
coefs.init.mat <- matrix(c(coefs.init$cnst,coefs.init$pm2.5,
                           coefs.init$temp,coefs.init$rh),
                         nrow=nrow(coefs.init),ncol=4,
                         dimnames=list(serials,c('Constant','PM2.5','Temperature','RH')))
coefs.fin.mat <- matrix(c(coefs.fin$cnst,coefs.fin$pm2.5,
                           coefs.fin$temp,coefs.fin$rh),
                         nrow=nrow(coefs.fin),ncol=4,
                         dimnames=list(serials,c('Constant','PM2.5','Temperature','RH')))
coefs.change <- (coefs.fin.mat - coefs.init.mat)/coefs.init.mat * 100
round(coefs.change,2)

# Mean percentage change for each coefficient across ODINs
round(colMeans(coefs.change),2)
```

## Plot Coefficients

```{r plot_coefs}
# Prepare for plotting
coefs.init$time <- rep('init',nrow(coefs.init))
coefs.fin$time <- rep('fin',nrow(coefs.fin))
coefs <- rbind(coefs.init,coefs.fin)

# Plot constant terms
ggplot(coefs, aes(x=odin.n,y=cnst,colour=time)) +
  geom_errorbar(aes(ymin=cnst-cnst.std, ymax=cnst+cnst.std)) + 
  geom_point() + 
  scale_colour_manual(values=c("red","blue"),name="Colocation",
                      labels=c(fin="Final",init="Initial")) + 
  ylab(expression("Constant")) +
  xlab("ODIN-SD Serial") +
  ggtitle(expression("Constant Term for Predicting"~PM[2.5]))

# Plot pm2.5.odin.x coefficients
ggplot(coefs, aes(x=odin.n,y=pm2.5,colour=time)) +
  geom_errorbar(aes(ymin=pm2.5-pm2.5.std, ymax=pm2.5+pm2.5.std)) + 
  geom_point() + 
  scale_colour_manual(values=c("red","blue"),name="Colocation",
                      labels=c(fin="Final",init="Initial")) + 
  ylab(expression(PM[2.5]~"Coefficient ("*mu*g^-1*m^3*")")) +
  xlab("ODIN-SD Serial") +
  ggtitle(expression(PM[2.5]~" (as measured by ODIN-SD) Coefficients for Predicting"
                     ~PM[2.5]))

# Plot rh.odin.x coefficients
ggplot(coefs, aes(x=odin.n,y=rh,colour=time)) +
  geom_errorbar(aes(ymin=rh-rh.std, ymax=rh+rh.std)) + 
  geom_point() + 
  scale_colour_manual(values=c("red","blue"),name="Colocation",
                      labels=c(fin="Final",init="Initial")) + 
  ylab("ODIN rh vs ECan PM2.5 Gradient") +
  xlab("ODIN-SD Serial") +
  ggtitle("ODIN vs ECan Linear Models for Initial and Final 2016 Colocation") +
  ylab("RH Coefficient (percentage"~point^-1*")") +
  xlab("ODIN-SD Serial") +
  ggtitle(expression("RH Coefficients for Predicting"~PM[2.5]))

# Plot temp.odin.x coefficients
ggplot(coefs, aes(x=odin.n,y=temp,colour=time)) +
  geom_errorbar(aes(ymin=temp-temp.std, ymax=temp+temp.std)) + 
  geom_point() + 
  scale_colour_manual(values=c("red","blue"),name="Colocation",
                      labels=c(fin="Final",init="Initial")) + 
  ylab(expression("Temperature Coefficient ("*degree*C^-1*")")) +
  xlab("ODIN-SD Serial") +
  ggtitle(expression("Temperature Coefficients for Predicting"~PM[2.5]))
```

## Plot Models

```{r plot_models}
for (serial in c(102,105,108)) {
  
  odin.vars <- paste0(c('pm2.5','temp','rh'),'.odin.',serial)
  eval(parse(text=paste0('form <- pm2.5 ~ ', paste(odin.vars,collapse='+'))))
  
  # Axis limits
  var.x.mins <- c(pm2.5=0,temp=0,rh=25)
  var.x.maxs <- c(pm2.5=100,temp=35,rh=100)
  var.y.min <- -10
  var.y.max <- 175
  
  # Initial and final model
  model.init <- lm(form,data=data.init)
  model.fin <- lm(form,data=data.fin)
  
  # Median dataframes
  medians.init <- data.frame()
  medians.fin <- data.frame()
  for (i in 1:3) {
    medians.init[1:2,odin.vars[i]] <- rep(median(data.init[,odin.vars[i]]),2)
    medians.fin[1:2,odin.vars[i]] <- rep(median(data.fin[,odin.vars[i]]),2)
  }

  # Axis labels
  xlabs.init <- list(pm2.5=substitute("ODIN-"*x~PM[2.5]~(mu*"g"~m^-3),list(x=serial)),
                     temp=substitute("ODIN-"*x~"Temperature ("*degree*"C)",
                                     list(x=serial)),
                     rh=substitute("ODIN-"*x~"RH (%)",list(x=serial))
             )
  xlabs.fin <- list(pm2.5=substitute("ODIN-"*x~PM[2.5]~(mu*"g"~m^-3),list(x=serial)),
                     temp=substitute("ODIN-"*x~"Temperature ("*degree*"C)",
                                     list(x=serial)),
                     rh=substitute("ODIN-"*x~"RH (%)",list(x=serial))
             )
  # Plot titles (omitted due to lack of space with side-by-side plots)
  titles.fin <- list(pm2.5=substitute("ODIN-SD"~x~"vs TEOM"~PM[2.5]~
                            "at Final Colocation",list(x=serial)),
                      temp=substitute("ODIN-SD"~x~" Temperature vs TEOM"~PM[2.5]~
                          "at Final Colocation",list(x=serial)),
                      rh=substitute("ODIN-SD"~x~" RH vs TEOM"~PM[2.5]~
                          "at Final Colocation",list(x=serial))
              )
  titles.init <- list(pm2.5=substitute("ODIN-SD"~x~"vs TEOM"~PM[2.5]~
                            "at Initial Colocation",list(x=serial)),
                      temp=substitute("ODIN-SD"~x~" Temperature vs TEOM"~PM[2.5]~
                          "at Initial Colocation",list(x=serial)),
                      rh=substitute("ODIN-SD"~x~" RH vs TEOM"~PM[2.5]~
                          "at Initial Colocation",list(x=serial))
              )

  for (i in 1:3) {

    # Initial plot
    df <- medians.init
    df[,odin.vars[i]] <- c(var.x.mins[i],var.x.maxs[i])
    line.df <- data.frame(x=df[,odin.vars[i]],y=predict(model.init,df))
    point.df <- data.frame(x=data.init[,odin.vars[i]],y=data.init[,"pm2.5"])
    p1 <- ggplot() +
      geom_point(data=point.df,aes(x,y),alpha=0.1) +
      geom_line(data=line.df,aes(x,y),colour="red") +
      xlim(var.x.mins[i],var.x.maxs[i]) +
      ylim(var.y.min,var.y.max) +
      xlab(xlabs.init[[i]]) +
      ylab(expression("TEOM"~PM[2.5]~(mu*'g'~m^-3))) +
      ggtitle("Initial Colocation") # titles.init[[i]]

    # Final plot
    df <- medians.fin
    df[,odin.vars[i]] <- c(var.x.mins[i],var.x.maxs[i])
    line.df <- data.frame(x=df[,odin.vars[i]],y=predict(model.fin,df))
    point.df <- data.frame(x=data.fin[,odin.vars[i]],y=data.fin[,"pm2.5"])
    p2 <- ggplot() +
      geom_point(data=point.df,aes(x,y),alpha=0.1) +
      geom_line(data=line.df,aes(x,y),colour="red") +
      xlim(var.x.mins[i],var.x.maxs[i]) +
      ylim(var.y.min,var.y.max) +
      xlab(xlabs.fin[[i]]) +
      ylab(expression("TEOM"~PM[2.5]~(mu*'g'~m^-3))) +
      ggtitle("Final Colocation") # titles.fin[[i]]

    # Plot
    grid.arrange(p1,p2,ncol=2)

  }
}
```