---
title: "Initial Colocation Model Selection"
author: "Hamish Huggard"
date: "February 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r book_keeping}
library(RPostgreSQL)
library(rpart)
library(reshape2)
library(zoo)
library(ggplot2)
library(mblm)
library(MASS)
library(rpart)

# Set working directory
setwd("c:\\Users\\Hammo\\Documents\\smoke emissions project\\code_final")

# Database login details (not in GitHub repo)
load("access.Rda")

# Connect to database
p <- dbDriver("PostgreSQL")
con <- dbConnect(p,
                 user=access$user,
                 password=access$pwd,
                 host='penap-data.dyndns.org',
                 dbname='cona',
                 port=5432)
```

```{r load_ecan}
# Load ECan data (stored locally)
ecan <- read.csv('RangioraWinter2016.csv',stringsAsFactors=FALSE)
names(ecan) <- c('date','time','wind.speed','wind.dir','wind.dir.std','wind.speed.std',
                 'wind.max','co','temp.ground','temp.2m','temp.6m','pm10',
                 'pm2.5','pm.course')
ecan$date <- as.POSIXct(ecan$date,format = '%m/%d/%Y %H:%M', tz='Etc/GMT-12')
ecan$time <- NULL # this is included in date
```

```{r load_odin}
# Load ODIN data
# Siteid = 18 is ECan site
odin.raw <-dbGetQuery(con,"SELECT d.recordtime AT TIME ZONE 'NZST' AS date,
                            i.serialn as serial, s.name as label,
                            d.value::numeric as val
                           FROM data.fixed_data as d,  
                            admin.sensor as s, admin.instrument as i
                           WHERE s.id = d.sensorid
                            AND s.instrumentid = i.id
                            AND i.name = 'ODIN-SD-3'
                            AND d.siteid = 18
                            AND (i.serialn = 'ODIN-102'
                             OR i.serialn = 'ODIN-103' 
                             OR i.serialn = 'ODIN-105'
                             OR i.serialn = 'ODIN-107'
                             OR i.serialn = 'ODIN-108'
                             OR i.serialn = 'ODIN-109'
                             OR i.serialn = 'ODIN-111'
                             OR i.serialn = 'ODIN-113'
                             OR i.serialn = 'ODIN-114'
                             OR i.serialn = 'ODIN-115')
                            AND (d.recordtime BETWEEN '2016-07-01 00:00 NZST'
                             AND '2016-08-01 00:00 NZST')
                            AND NOT (d.recordtime BETWEEN '2016-09-25 02:00 NZST'
                             AND '2016-09-25 03:00 NZST')
                            AND (s.name = 'PM2.5'
                             OR s.name = 'Temperature'
                             OR s.name = 'RH')
                           ORDER BY date;") 

# Time periods including timestamps between 2016-09-25 02:01 and 02:59 
# will truncate timestamps at 'day'.

# Get rid of the seconds
odin.raw$date <- trunc(odin.raw$date,'min')
# The above converted it to POSIXlt
odin.raw$date <- as.POSIXct(odin.raw$date)

# Fix daylight savings bug
ds.time <- as.POSIXct('09/25/2016 02:00',format = '%m/%d/%Y %H:%M', tz='Etc/GMT-12')
odin.raw[odin.raw$date > ds.time, 'date'] <- odin.raw[odin.raw$date > ds.time, 'date'] + 60*60
```

```{r merge}
serials <- unique(odin.raw$serial)

data <- ecan

for (i in 1:length(serials)) {
  
  # Get data for one ODIN in wide format
  odin <- dcast(odin.raw[odin.raw$serial==serials[i],], 
                     date~label, value.var='val', fun.aggregate=mean)
  
  # Make column names easier to type
  names(odin) <- tolower(names(odin))
  names(odin)[which(names(odin)=="temperature")] <- "temp"
  
  # Change columns from "temp"" to "temp.odin.100", etc
  serial <- substring(serials[i],6,8)
  names(odin) <- paste0(names(odin),'.odin.',serial)
  
  # The 'date.odin.100' back to just 'date'
  date.odin.100 <- paste0('date.odin.',serial)
  odin[,'date'] <- odin[,date.odin.100]
  odin[,date.odin.100] <- NULL
  
  # Make sure that there is a odin entry for each minute
  dates <- data.frame(date=seq(odin$date[1],odin$date[nrow(odin)],by='mins'))
  odin <- merge(odin,dates,by="date",all=TRUE)
  
  # Change the ODIN measurements from 1 min averages to 1 hour averages
  date.col <- which(names(odin)=='date')
  odin.zoo <- zoo( odin[,-date.col] ) # remove date because rollapply only works on numerics
  odin.zoo <- rollapply(odin.zoo,width=60,by=1,FUN=mean,align="left",na.rm=TRUE)
  # NB I don't know what the 'align' parameter does
  odin <- odin[1:nrow(odin.zoo),]
  odin[,-date.col] <- odin.zoo
  # Take timestamps at the end of the hour average following ECan convention
  odin$date <- odin$date + 60*60
  
  # Merge with the rest of the data
  data <- merge(data,odin,by='date',all=FALSE)
}

# Split dataset into halves
pivot <- as.integer(nrow(data)/2)
data.1 <- data[1:pivot,]
data.2 <- data[(pivot+1):nrow(data),]
```

## Testing Modeling Techniques

```{r try_models}
models <- list(NA,NA,NA,NA,NA)
names(models) <- c("linear","robust linear","quadratic","cubic","reg tree")

mse <- array(NA,dim=c(length(serials)+1,length(models),3),
              dimnames=list(c(serials,'avg'),names(models),c('data.1','data.2','avg')))

for (j in 1:2) {
  for (i in 1:length(serials)) {
    
    # Does test data = data.1 or data.2?
    test <- 3-j
    
    # Linear formula
    in.vars <- paste0(c('pm2.5','temp','rh'),'.odin.',substring(serials[i],6,8))
    eval(parse(text=paste0("form <- pm2.5 ~ ",paste0(in.vars,collapse='+'))))
    
    # Quadratic formula
    quad.in.vars <- paste0("poly(",in.vars,",2)")
    eval(parse(text=paste0("quad.form <- pm2.5 ~ ",paste0(quad.in.vars,collapse='+'))))
    
    # Cubic formula
    cub.in.vars <- paste0("poly(",in.vars,",3)")
    eval(parse(text=paste0("cub.form <- pm2.5 ~ ",paste0(cub.in.vars,collapse='+'))))
    
    # Test and training data
    eval(parse(text=paste0("test.data <- data.",j)))
    eval(parse(text=paste0("train.data <- data.",3-j)))
    
    # Linear model
    models[['linear']] <- lm(form,data=train.data)
    y.hat <- predict(models[['linear']],test.data)
    mse[i,'linear',j] <- mean((test.data$pm2.5-y.hat)^2,na.rm=TRUE)
    
    # Robust linear model
    models[['robust linear']] <- rlm(form,data=train.data)
    y.hat <- predict(models[['robust linear']],test.data)
    mse[i,'robust linear',j] <- mean((test.data$pm2.5-y.hat)^2,na.rm=TRUE)
    
    # Quadratic model
    models[['quadratic']] <- lm(quad.form,data=train.data)
    y.hat <- predict(models[['quadratic']],test.data)
    mse[i,'quadratic',j] <- mean((test.data$pm2.5-y.hat)^2,na.rm=TRUE)
    
    # Cubic model
    models[['cubic']] <- lm(cub.form,data=train.data)
    y.hat <- predict(models[['cubic']],test.data)
    mse[i,'cubic',j] <- mean((test.data$pm2.5-y.hat)^2,na.rm=TRUE)
    
    # Regression Tree
    models[['reg tree']] <- rpart(form,data=train.data,method='anova')
    y.hat <- predict(models[['reg tree']],test.data,'vector')
    mse[i,'reg tree',j] <- mean((test.data$pm2.5-y.hat)^2,na.rm=TRUE)
    
    
    # Plotting models (finish if I have time)
    
    # # Datapoints for plot lines
    # pm2.5 <- data[,in.vars[1]]
    # pm2.5.range <- min(pm2.5):max(pm2.5)
    # plot.df <- data.frame(x=NA,y=NA,model=NA)
    # for (k in 1:length(models)) {
    #   y <- predict(models[[k]],)
    #   x <- data.frame(x)
    #   plot.df <- rbind(plot.df,x)
    # }
    
    
  }
  
  # Find average accross ODINs
  for (i in 1:length(models)) {
    mse['avg',i,j] <- mean(mse[,i,j],na.rm=TRUE)
  }
}

# Fill in the averages matrix
for (i in 1:(length(serials)+1)) {
  for (j in 1:length(models)) {
    mse[i,j,3] <- mean(c(mse[i,j,1],mse[i,j,2]))
  }
}

mse <- round(mse,2)

mse
```