---
title: "Timing of calibration"
author: "Hamish Huggard"
date: "February 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data

```{r book_keeping}
library(RPostgreSQL)
library(rpart)
library(reshape2)
library(zoo)
library(ggplot2)
library(MASS)
library(gridExtra)

# Set working directory
setwd("c:\\Users\\Hammo\\Documents\\smoke emissions project\\code_final")

# Database login details (not in GitHub repo)
load("access.Rda")

# Connect to database
p <- dbDriver("PostgreSQL")
con <- dbConnect(p,
                 user=access$user,
                 password=access$pwd,
                 host='penap-data.dyndns.org',
                 dbname='cona',
                 port=5432)
```

```{r load_ecan}
# Load ECan data (stored locally)
ecan <- read.csv('RangioraWinter2016.csv',stringsAsFactors=FALSE)
names(ecan) <- c('date','time','wind.speed','wind.dir','wind.dir.std','wind.speed.std',
                 'wind.max','co','temp.ground','temp.2m','temp.6m','pm10',
                 'pm2.5','pm.course')
ecan$date <- as.POSIXct(ecan$date,format = '%m/%d/%Y %H:%M', tz='Etc/GMT-12')
ecan$time <- NULL # this is included in date
```

```{r load_odin}
# ECan site has siteid=18
odin.raw <-dbGetQuery(con,"SELECT d.recordtime AT TIME ZONE 'NZST' AS date,
                            i.serialn as serial, s.name as label,
                            d.value::numeric as val
                           FROM data.fixed_data as d,  
                            admin.sensor as s, admin.instrument as i
                           WHERE s.id = d.sensorid
                            AND s.instrumentid = i.id
                            AND i.name = 'ODIN-SD-3'
                            AND d.siteid = 18
                            AND (i.serialn = 'ODIN-109')
                            AND (d.recordtime BETWEEN '2016-07-11 00:00 NZST'
                              AND '2017-07-26 00:00 NZST')
                            AND NOT (d.recordtime BETWEEN '2016-09-25 02:00 NZST'
                             AND '2016-09-25 03:00 NZST')
                            AND (s.name = 'PM2.5'
                             OR s.name = 'Temperature'
                             OR s.name = 'RH')
                           ORDER BY date;") 

# 02:01 to 02:59 on 2016-09-25 is excluded because this is when the switch to NZST occurs.
# Without the exclusion clause the timestamps will truncate at 'day'.

# Truncate seconds from timestamps
odin.raw$date <- trunc(odin.raw$date,'min')
odin.raw$date <- as.POSIXct(odin.raw$date) # the above converted it to POSIXlt

# Fix daylight savings bug
ds.time <- as.POSIXct('09/25/2016 02:00',format = '%m/%d/%Y %H:%M', tz='Etc/GMT-12')
odin.raw[odin.raw$date > ds.time, 'date'] <- 
  odin.raw[odin.raw$date > ds.time, 'date'] + 60*60
```

## Preprocessing

```{r odin_preprocessing}
odin <- dcast(odin.raw, date~label, value.var='val', fun.aggregate=mean)

# Make column names easier to type
names(odin) <- tolower(names(odin))
names(odin)[which(names(odin)=="temperature")] <- "temp"
```

```{r merge}
data <- ecan

# Make sure that there is a odin entry for each minute
dates <- data.frame(date=seq(odin$date[1],odin$date[nrow(odin)],by='mins'))
odin <- merge(odin,dates,by="date",all=TRUE)

# Change the ODIN measurements from 1 min averages to 1 hour averages
odin.zoo <- zoo( odin[,2:ncol(odin)] )
odin.roll.apply <- rollapply(odin.zoo,width=60,by=1,FUN=mean,align="left",na.rm=TRUE)
odin.avgs <- odin[1:nrow(odin.roll.apply),]
odin.avgs[,2:ncol(odin)] <- odin.roll.apply

# Take timestamps at the end of the hour average following ECan convention
odin.avgs$date <- odin.avgs$date + 60*60 

# Purge NaNs
odin.avgs <- odin.avgs[!is.nan(odin.avgs$pm2.5),]
odin.avgs <- odin.avgs[!is.nan(odin.avgs$rh),]
odin.avgs <- odin.avgs[!is.nan(odin.avgs$temp),]
names(odin.avgs) <- c('date',paste0(names(odin.avgs)[2:ncol(odin.avgs)],'.odin.109'))
data <- merge(data,odin.avgs,by='date',all=FALSE)
```

## Calibration duration

```{r calibration_duration}
max.days <- 40

# Use 24 hour periods starting and ending at noon
date.lt <- as.POSIXlt(data$date)
noons <- data[which(date.lt$hour==12 & date.lt$min==0),'date']
start.date <- noons[1]
end.date <- noons[length(noons)]
day <- as.POSIXct('1/1/2') - as.POSIXct('1/1/1')
week <- day * 7
month <- week*4

mse <- data.frame(days=NA,mse=NA)
mse[1:max.days,'days'] <- 1:max.days

mse2 <- matrix(NA,ncol=31,nrow=max.days)
for (i in 1:max.days) {
  for (j in 0:30) {
    train.inds <- which(start.date + day*i + day*j < data$date &
                          data$date < start.date + day*i + day*j + week)
    test.inds <- which(start.date + day*i + day*j + week < data$date &
                          data$date < start.date + day*i + day*j + week + month)
    train.data <- data[train.inds,]
    test.data <- data[-train.inds]
    model <- rlm(pm2.5~pm2.5.odin.109+temp.odin.109+rh.odin.109,data=train.data)
    y.hat <- predict(model,test.data)
    mse2[i,j+1] <- mean((test.data$pm2.5-y.hat)^2,na.rm=TRUE)
  }
  
  mse[i,'mse'] <- mean(mse2[i,])
  
}

mse

summary(lm(mse~days,data=mse))$coefficients

# Plot

ggplot(mse,aes(days,mse)) +
  geom_line() +
  ylab("MSE") +
  xlab("Days of Training Data Used") +
  ggtitle("MSE of ODIN-109 Model with Varying-Sized Window of Training Data") +
  geom_smooth(method="lm")
```

## Calibration Timing

```{r timing}
# Calibrating using one week of data
mse.week <- data.frame(date=noons[1],mse=NA)
mse.month <- data.frame(date=noons[1],mse=NA)
no.days <- floor( (data$date[nrow(data)]-data$date[1]) )-30

for (i in 1:no.days) {
  # Week long window
  train.inds <- which(start.date + i*day < data$date & 
                        data$date < start.date + i*day + week)
  train.data <- data[train.inds,]
  test.data <- data[-train.inds,]
  model <- rlm(pm2.5~pm2.5.odin.109+temp.odin.109+rh.odin.109,data=train.data)
  y.hat <- predict(model,test.data)
  mse.week[i,'mse'] <- mean((test.data$pm2.5-y.hat)^2,na.rm=TRUE)
  mse.week[i,'date'] <- train.data[1,'date']
  
  # Month long window
  train.inds <- which(start.date + i*day < data$date & 
                        data$date < start.date + i*day + month)
  train.data <- data[train.inds,]
  test.data <- data[-train.inds,]
  model <- rlm(pm2.5~pm2.5.odin.109+temp.odin.109+rh.odin.109,data=train.data)
  y.hat <- predict(model,test.data)
  mse.month[i,'mse'] <- mean((test.data$pm2.5-y.hat)^2,na.rm=TRUE)
  mse.month[i,'date'] <- train.data[1,'date']
}

# Plot the month and week data together
mse.week[,'duration'] <- rep("Week",nrow(mse.week))
mse.month[,'duration'] <- rep("Month",nrow(mse.month))

ggplot(rbind(mse.week,mse.month)) +
  geom_line(aes(date,mse,colour=duration)) +
  xlab("Start Date of Training Data") +
  ylab("MSE") +
  ggtitle("MSE of ODIN-109 Model with Sliding Window of Training Data") +
  scale_colour_manual("Window length",values=c("red","blue"))

# Look at linear models

# Convert date from seconds to days with 0 = initial date
mse.week$date2 <- (mse.week$date-mse.week$date[1])/24/60/60 
mse.month$date2 <- (mse.week$date-mse.month$date[1])/24/60/60 
summary(lm(mse~date2,data=mse.week))$coefficients
summary(lm(mse~date2,data=mse.month))$coefficients
# Start date is...
mse.week$date[1]
mse.month$date[1]
```