---
title: "Clock Synchronization"
author: "Hamish Huggard"
date: "January 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data

```{r book_keeping}
library(RPostgreSQL)
library(rpart)
library(reshape2)
library(zoo)
library(ggplot2)

# Set working directory
setwd("c:\\Users\\Hammo\\Documents\\smoke emissions project\\repo")

# Database login details (not in GitHub repo)
load("access.Rda")

# Connect to database
p <- dbDriver("PostgreSQL")
con <- dbConnect(p,
                 user=access$user,
                 password=access$pwd,
                 host='penap-data.dyndns.org',
                 dbname='cona',
                 port=5432)
```

```{r load_ecan}
# Load ECan data (stored locally)
ecan <- read.csv('RangioraWinter2016.csv',stringsAsFactors=FALSE)
names(ecan) <- c('date','time','wind.speed','wind.dir','wind.dir.std','wind.speed.std',
                 'wind.max','co','temp.ground','temp.2m','temp.6m','pm10',
                 'pm2.5','pm.course')
ecan$date <- as.POSIXct(ecan$date,format = '%m/%d/%Y %H:%M', tz='Etc/GMT-12')
ecan$time <- NULL # this is included in date
```

```{r load_odin}
# Load ODIN measurements from June 2017
siteid = 18 # ecan site
odin.raw <-dbGetQuery(con,"SELECT d.recordtime AT TIME ZONE 'NZST' AS date,
                            i.serialn as serial, s.name as label,
                            d.value::numeric as val
                           FROM data.fixed_data as d,  
                            admin.sensor as s, admin.instrument as i
                           WHERE s.id = d.sensorid
                            AND s.instrumentid = i.id
                            AND i.name = 'ODIN-SD-3'
                            AND d.siteid = 18
                            AND (d.recordtime BETWEEN '2016-01-01 00:00 NZST'
                             AND '2017-01-01 00:00 NZST')
                            AND NOT (d.recordtime BETWEEN '2016-09-25 02:00 NZST'
                             AND '2016-09-25 03:00 NZST')
                            AND (s.name = 'PM2.5'
                             OR s.name = 'PM10'
                             OR s.name = 'Temperature'
                             OR s.name = 'RH')
                           ORDER BY date;") 

# 2016-09-25 02:01 to 02:59 is excluded because this is when the NZST to NZDT change occurs.
# Including this leads to truncation of dates at "day".

odin.raw$date <- trunc(odin.raw$date,'min') # get rid of the seconds
odin.raw$date <- as.POSIXct(odin.raw$date) # the above converted it to POSIXlt

# this helps somehow
ds.time <- as.POSIXct('09/25/2016 02:00',format = '%m/%d/%Y %H:%M', tz='Etc/GMT-12')
odin.raw[odin.raw$date > ds.time, 'date'] <- odin.raw[odin.raw$date > ds.time, 'date'] + 60*60
```

```{r odin_preprocessing}
# Create a data frame for each ODIN
serials <- unique(odin.raw$serial)
odins <- list()
for (i in 1:length(serials)) {
  this.odin <- dcast(odin.raw[odin.raw$serial==serials[i],], 
                     date~label, value.var='val', fun.aggregate=mean)
  # Make column names easier to type
  names(this.odin) <- tolower(names(this.odin))
  names(this.odin)[which(names(this.odin)=="temperature")] <- "temp"
  odins[[i]] <- this.odin
}
# change ODIN serials from ODIN-101 to odin.101
# the hyphens cause problems by being interpreted as minuses
tidy.serial <- function(serialn) paste0('odin.',substring(serialn,6,8))
names(odins) <- sapply(serials,FUN=tidy.serial)
```


```{r synchronize}
best.offsets <- data.frame(odin=NA,pm2.5=NA,pm10=NA,temp=NA)
# correlation between measurements with zero offset
corr0 <- data.frame(odin=NA,pm2.5=NA,pm10=NA,temp=NA,no=NA) 

for (j in 1:length(odins)) {
  odin <- odins[[j]]
  # make sure that there is a odin entry for each minute
  dates <- data.frame(date=seq(odin$date[1],odin$date[nrow(odin)],by='mins'))
  odin <- merge(odin,dates,by="date",all=TRUE)
  if (nrow(odin) != nrow(dates))
    print("Oh noes! Gaps in ODIN data!")
  # if there are gaps merge "dates" with odin
  
  # change the ODIN measurements from 1 min averages to 1 hour averages
  odin.zoo <- zoo( odin[,2:ncol(odin)] ) # remove date because rollapply only works on numerics
  odin.roll.apply <- rollapply(odin.zoo,width=60,by=1,FUN=mean,align="left",na.rm=TRUE)
  # NB I don't know what the 'align' parameter does
  # Throw out data for which there is not a complete hour window
  odin.avgs <- odin[1:nrow(odin.roll.apply),]
  odin.avgs[,2:ncol(odin)] <- odin.roll.apply
  # NB if there are gaps in the data then this will be screwed up
  odin.avgs$date <- odin.avgs$date + 60*60 # take timestamps at the end of the hour average following ECan convention
  
  # Find best correlation between ECan and ODIN
  
  offsets <- -120:120
  blank <- rep(NA,length(offset))
  corr.df <- data.frame(offset=offsets,temp=blank,pm2.5=blank,pm10=blank)
  for (i in 1:nrow(corr.df)) {
    offset <- corr.df[i,'offset']
    odin.i <- odin.avgs
    odin.i$date <- odin.i$date + offset*60
    names(odin.i) <- c('date',paste0(names(odin.i),'.odin')[2:ncol(odin)])
    data.i <- merge(odin.i,ecan,by='date',all=FALSE)
    corr.df[i,'temp'] <- cor(data.i$temp.2m,data.i$temp.odin,
                             method="pearson",use="complete.obs")
    corr.df[i,'pm2.5'] <- cor(data.i$pm2.5,data.i$pm2.5.odin,
                             method="pearson",use="complete.obs")
    corr.df[i,'pm10'] <- cor(data.i$pm10,data.i$pm10.odin,
                             method="pearson",use="complete.obs")
  }
  
  odin.name <- names(odins)[j]
  best.offsets[j,'odin'] <- odin.name
  best.offsets[j,'temp'] <- corr.df[which.max(corr.df[,'temp']),'offset']
  best.offsets[j,'pm2.5'] <- corr.df[which.max(corr.df[,'pm2.5']),'offset']
  best.offsets[j,'pm10'] <- corr.df[which.max(corr.df[,'pm10']),'offset']
  
  print(best.offsets[j,])
  
  no <- length(which(!is.na(data.i$pm2.5.odin)))
  
  corr0[j,'odin'] <- odin.name
  corr0[j,'temp'] <- corr.df[corr.df$offset==0,'temp']
  corr0[j,'pm2.5'] <- corr.df[corr.df$offset==0,'pm2.5']
  corr0[j,'pm10'] <- corr.df[corr.df$offset==0,'pm10']
  corr0[j,'no'] <- no
  
  print(corr0[j,])
  
  print(paste("Number of colocated data points",no))
  
  corr.melt <- melt(corr.df,id='offset')
  the.plot <- ggplot(corr.melt) + 
                geom_line(aes(x=offset,y=value,colour=variable)) +
                scale_colour_manual("Variable",values=c("red","green","blue"),
                                    labels=c("Temperature",expression(PM[2.5]),
                                             expression(PM[10]))) + 
                ylab("Pearson Correlation") +
                xlab("Offset (minutes)") +
                ggtitle(paste0("Correlation Between ECan and ODIN-",
                              substr(odin.name,6,8)," Measurements"))
  print(the.plot)
  
  best.offset <- corr.df[which.max(corr.df[,'pm2.5']),'offset'] 

  odin.bo <- odin.avgs # bo = best offset
  odin.bo$date <- odin.bo$date + best.offset*60
  names(odin.bo) <- c('date',paste0(names(odin.bo),'.',names(odins)[j])[2:ncol(odin)])
}

best.offsets
summary(best.offsets$pm2.5)
summary(best.offsets$pm10)
summary(best.offsets$temp)

corr0
```
